is_debug: true
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 5000
secret_crypto:
mongodb_config:
  host:
  port:
  database: user-service
  collection: users
  username:
  password:
  auth_db:
  atlas_uri:
postgresql_config:
  host: localhost
  port: 5432
  database: user-service
  username: postgres
  password: postgres
