is_debug: true
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 5000
mongodb:
  username:
  password:
  database: user-service
  collection: users
  auth_db:
  host:
  port:
  atlas_uri:
secret_crypto:
